#!/usr/bin/env bash
# Requirements:

# - Install nginx on your web-01
# - server
# - Nginx should be listening on port 80
# - When querying Nginx at its root / with a GET request (requesting a page) using curl, it must return a page that contains the string Hello World!
# - As an answer file, write a Bash script that configures a new Ubuntu machine to respect above requirements (this script will be run on the server itself)
# - You can’t use systemctl for restarting nginx


# Install nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Create a page that contains the string Hello World!
touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html

# Create a new file in /etc/nginx/sites-available/
sudo touch /etc/nginx/sites-available/default

# Add the following content to the file
printf %s "server {
    listen		80 default_server;
    listen		[::]:80 default_server;

    root		/var/www/html;
    index		index.html index.htm index.nginx-debian.html;
}
" > /etc/nginx/sites-available/default

# Restart nginx
sudo service nginx restart

