#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to respect above requirements (this script will be run on the server itself)

# Install Nginx
apt-get update
apt-get -y install nginx

# Configure Nginx
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    location / {
        add_header Cache-Control no-cache;
        return 200 'Hello World!';
        }
    }" > /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart

