#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

# Requirements:

# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
# Make sure that HAproxy can be managed via an init script
# Make sure that your servers are configured with the right hostnames: [STUDENT_ID]-web-01 and [STUDENT_ID]-web-02. If not, follow this tutorial.
# For your answer file, write a Bash script that configures a new Ubuntu machine to respect above requirements

# Update and install HAproxy
sudo apt-get update -y
sudo apt-get install -y haproxy

# Configure HAproxy
printf %s "
frontend lb-01
    bind *:80
    mode http
    default_backend webservers

backend webservers
    mode http
    balance roundrobin
    server 404031-web-01 34.232.69.100:80 check
    server 404031-web-02 100.26.173.88:80 check
" | sudo tee /etc/haproxy/haproxy.cfg

sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Restart HAproxy
sudo service haproxy restart
