#!/usr/bin/env bash
# Bash script that configures a server to the below requirements
# Nginx must be running, and listening on port 80 of all the server’s active IPv4 IPs
sudo apt update -y
sudo apt install nginx -y
new="80 default_server"
old="8080 default_server"
sed -i "s/$old/$new/" /etc/nginx/sites-enabled/default
service nginx start

