#!/usr/bin/env bash
# service (init) must say that nginx is not running ← for real
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
sudo rm -f /var/run/nginx.pid
