#!/usr/bin/env bash
# Bash script that:
#  Creates the file /var/run/myscript.pid containing its PID
#  Displays To infinity and beyond indefinitely
#  Displays I hate the kill command when receiving a SIGTERM signal
#  Displays Y U no love me?! when receiving a SIGINT signal
#  Deletes the file /var/run/myscript.pid and
#  terminates itself when receiving a SIGQUIT or SIGTERM signal

PID_FILE="/var/run/myscript.pid"

# Function to handle signals
handle_signal() {
	if [ "$1" = "SIGTERM" ] || [ "$1" = "SIGQUIT" ];
	then
		echo "Deleting PID file and exiting..."
        	rm -f "$PID_FILE"
        	exit 0
	elif [ "$1" = "SIGTERM" ];
	then
		echo "I hate the kill command"
	elif [ "$1" = "SIGINT" ];
	then
		echo "Y U no love me?!"
	fi
}

# Trap signals
trap 'handle_signal SIGTERM' SIGTERM
trap 'handle_signal SIGQUIT' SIGQUIT
trap 'handle_signal SIGINT' SIGINT

echo $$ > "$PID_FILE"

while true;
do
	echo "To infinity and beyond"
	sleep 1
done

