#!/usr/bin/env bash
# Bash script that:
#  Creates the file /var/run/myscript.pid containing its PID
#  Displays To infinity and beyond indefinitely
#  Displays I hate the kill command when receiving a SIGTERM signal
#  Displays Y U no love me?! when receiving a SIGINT signal
#  Deletes the file /var/run/myscript.pid and
#  terminates itself when receiving a SIGQUIT or SIGTERM signal

PID_FILE="/var/run/myscript.pid"

# Function to handle termate
handle_terminate() {
	rm -f "$PID_FILE"
        exit
}

echo $$ > "$PID_FILE"

while true;
do
	echo "To infinity and beyond"
	sleep 1
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command" && handle_terminate' SIGTERM
	trap 'terminator' SIGQUIT
done

