#!/usr/bin/env bash
# Write Bash (init) script 101-manage_my_process that manages manage_my_process.
# (both files need to be pushed to git)

# Requirements:

# When passing the argument start:
#  Starts manage_my_process
#  Creates a file containing its PID in /var/run/my_process.pid
#  Displays manage_my_process started
# When passing the argument stop:
#  Stops manage_my_process
#  Deletes the file /var/run/my_process.pid
#  Displays manage_my_process stopped
# When passing the argument restart
#  Stops manage_my_process
#  Deletes the file /var/run/my_process.pid
#  Starts manage_my_process
#  Creates a file containing its PID in /var/run/my_process.pid
#  Displays manage_my_process restarted

# Displays Usage: manage_my_process {start|stop|restart}
# if any other argument or no argument is passed

PID_FILE="/var/run/my_process.pid"

start() {
	./manage_my_process &
	echo "$!" > "$PID_FILE"
}

stop() {
	sudo kill -15 "$(cat "$PID_FILE")" && rm -f "$PID_FILE"
}

case "$1" in 
	start)
		start
		echo "manage_my_process started"
	;;
	stop)
		stop
		echo "manage_my_process stopped"
	;;
	restart)
		stop
		start
		echo "manage_my_process restarted"
	;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
esac

exit 0

