#!/usr/bin/env bash
# Displays the contents of the file `/etc/passwd`.
#   Only displays the username, user id, and user home directory path.

while IFS=: read -r username _ uid _ _ home _;
do
	echo "$username:$uid:$home"
done < /etc/passwd

