#!/usr/bin/env bash
# Gracefully reloads Gunicorn

# Check the status of the gunicorn service, extract the Main PID using grep and cut, then send the HUP signal to that PID using xargs and kill.
systemctl status gunicorn | grep -oE 'Main PID: [0-9]+' | cut -d ' ' -f3 | xargs kill -HUP

